apiVersion: v1
kind: Secret
metadata:
  name: booking-api
type: Opaque
stringData:
  ConnectionStrings__BookingDb: "Host=raspikube0;Username=booking;Password=booking;Database=booking;"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-api
data:
  CORS__ALLOWEDORIGINS: "localhost:3000, raspikube0:3080, raspikube0:3000"

---

apiVersion: v1
kind: Service
metadata:
  name: booking-api
spec:
  type: LoadBalancer
  selector:
    app: booking-api
  ports:
  - port: 3080
    targetPort: booking-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-api
  template:
    metadata:
      labels:
        app: booking-api
    spec:
      containers:
      - name: booking-api
        image: maxandriani/booking-app-server:0.0.0-rc4
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: booking-api
          - secretRef:
              name: booking-api
        ports:
          - containerPort: 80
            name: booking-api

